### ISSUE TITLE
Develop Fitness Tracker ER Diagram

### ISSUE THREAD

**Issue by DuganZabran** [DuganZabran/CSCI-466-Final-Project#1]
[Fitness Tracker Er Diagram.pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4471814/Fitness.Tracker.Er.Diagram.pdf)

**Comment by DuganZabran** [comment]
Necessary Views are REQUIREMENTS.
Drawing of graph not required.

**Comment by Parkerps** [comment]
ER Diagram
[ER_Diagram_group_project.pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4476726/ER_Diagram_group_project.pdf)

**Comment by Parkerps** [comment]
Updated ER diagram

[ER_Diagram_group_project (3).pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4489026/ER_Diagram_group_project.3.pdf)

**Comment by Parkerps** [comment]
Updated the ER Diagram
[ER_Diagram_group_project (4).pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4489518/ER_Diagram_group_project.4.pdf)
