### ISSUE TITLE
Description of Attributes in ER Diagram

### ISSUE THREAD

**Issue by DuganZabran** [DuganZabran/CSCI-466-Final-Project#2]
Should include the purpose of the data, as well as a description of its domain.

**Comment by Parkerps** [comment]
[CSCI 466 relational diagram group project writeup.pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4481741/CSCI.466.relational.diagram.group.project.writeup.pdf)

**Comment by Parkerps** [comment]
Updated Discription of attributes for the ER Diagram. The PDF is the copy to turn in, and the docx is for updating if needed.
[CSCI 466 relational diagram group project writeup.pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4494240/CSCI.466.relational.diagram.group.project.writeup.pdf)
[CSCI 466 relational diagram group project writeup.docx](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4494241/CSCI.466.relational.diagram.group.project.writeup.docx)
