### ISSUE TITLE
ER Diagram Relational Schema

### ISSUE THREAD

**Issue by DuganZabran** [DuganZabran/CSCI-466-Final-Project#3]
Needs to be in 3rd Normal Form

**Comment by daeclerck** [comment]
[Group_Relational_Schema.pdf](https://github.com/DuganZabran/CSCI-466-Final-Project/files/4477198/Group_Relational_Schema.pdf)

**Comment by Editalthte** [comment]
![Final Project Database Mockup](https://user-images.githubusercontent.com/8879949/79387353-2939cb80-7f31-11ea-8b6c-7a18bb8ea848.png)
